apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.requestService.name }}-config"
data:
    SENTINEL_ADDRESS: {{ .Values.config.sentinelAddress }} 
    SENTINEL_MASTER: {{ .Values.config.sentinelMaster }}
    APP_SERVER_ADDRESS: {{ .Values.requestService.config.appServerAddress }}:{{ .Values.requestService.config.appServerPort }}
    INFLUX_ADDRESS: {{ .Values.config.influxDBUrl }}
    INFLUX_DB: {{ .Values.config.influxDB }}
    LOG_LEVEL: {{ .Values.requestService.logLevel }}
