apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.requestService.name }}-secret"
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.config.redisPassword | b64enc }}
  SENTINEL_PASSWORD: {{ .Values.config.sentinelPassword | b64enc }}
  INFLUX_USER: {{ .Values.config.influxDBUser | b64enc }}
  INFLUX_PASSWORD: {{ .Values.config.influxDBPassword | b64enc }}
