apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.requestService.name }}
  name: {{ .Values.requestService.name }}
spec:
  ports:
  - name: {{ .Values.requestService.config.appServerPort }}-8080
    port: 8080
    protocol: TCP
    targetPort: {{ .Values.requestService.config.appServerPort }}
    # nodePort: {{ .Values.requestService.nodePort }} 
  selector:
    app: {{ .Values.requestService.name }}
  type: ClusterIP