apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.cacheService.name }}
  name: {{ .Values.cacheService.name }}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.cacheService.name }}
  type: ClusterIP