apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.cacheService.name }}-secret"
type: Opaque
data:
    ARANGO_DB_USER: {{ .Values.config.arangoDBUser | b64enc }}
    ARANGO_DB_PASSWORD: {{ .Values.config.arangoDBPassword | b64enc }}
    REDIS_PASSWORD: {{ .Values.config.redisPassword | b64enc }}
    SENTINEL_PASSWORD: {{ .Values.config.sentinelPassword | b64enc }}