apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.proxy.name }}
  name: {{ .Values.proxy.name }}
spec:
  ports:
  - name: {{ .Values.subscriptionService.name }}
    port: {{ .Values.proxy.config.externalSubscriptionServicePort }}
    protocol: TCP
    targetPort: {{ .Values.proxy.config.internalSubscriptionServicePort }}
  - name: {{ .Values.requestService.name }}
    port: {{ .Values.proxy.config.externalRequestServicePort }}
    protocol: TCP
    targetPort: {{ .Values.proxy.config.internalRequestServicePort }}
  selector:
    app: {{ .Values.proxy.name }}
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.proxy.config.loadBalancerIP }}"