imagePullSecrets: []

release:
  cacheServiceTag: dev-30
  requestServiceTag: dev-30
  subscriptionServiceTag: dev-30

config:
  arangoDB: jalapeno-arangodb.jalapeno.svc.cluster.local:8086
  arangoDBUser: root
  arangoDBPassword: jalapeno
  arangoDBName: jalapeno
  redisPassword: a-very-complex-password-here
  sentinelPassword: a-very-complex-password-here
  sentinelAddress: jagw-redis.jagw-dev-dominique.svc.cluster.local:26379
  sentinelMaster: mymaster
  kafkaAddress: kafka.jalapeno.svc.cluster.local:9092
  influxDBUrl: influxdb.jalapeno.svc.cluster.local:8086
  influxDBUser: root
  influxDBPassword: jalapeno
  influxDB: mdt_db

subscriptionService:
  name: subscription-service
  replicas: 1
  image:
    repository: insost/jagw-subscription-service
    pullPolicy: Always
  resources: []
  nodePort: 30060
  config:
    appServerAddress: 0.0.0.0
    appServerPort: 9000
  logLevel: trace

cacheService:
  name: cache-service
  replicas: 1
  image:
    repository: insost/jagw-cache-service
    pullPolicy: Always
  resources: []
  logLevel: trace

requestService:
  name: request-service
  replicas: 1
  image:
    repository: insost/jagw-request-service
    pullPolicy: Always
  resources: []
  nodePort: 30061
  config:
    appServerAddress: 0.0.0.0
    appServerPort: 9000
  logLevel: trace


# Official bitnami/stable charts
# The charts are defined in the Charts.yaml as dependency
# https://artifacthub.io/packages/helm/bitnami/redis
redis:
  global:
    redis:
      password: a-very-complex-password-here
  
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.0.4-debian-11-r17

  sentinel:
    enabled: true

proxy:
  name: envoy-proxy
  replicas: 1
  image:
    #repository: envoyproxy/envoy-dev
    repository: envoyproxy/envoy
    pullPolicy: Always
    #tag: f9d936ec65e42308f72b48e52ed5b810effc40e5
    tag: v1.20.7
  resources: []
  config:
    appServerAddress: 0.0.0.0
    appServerPort: 9901
    internalSubscriptionServicePort: 9902
    externalSubscriptionServicePort: 30051
    internalRequestServicePort: 9903
    externalRequestServicePort: 30050
