apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.redis.port}}
    targetPort: {{ .Values.redis.port }}
    name: {{ .Values.redis.name }}
  selector:
    app: {{ .Values.redis.name }}