apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sentinel.name }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.sentinel.port }}
    targetPort: {{ .Values.sentinel.port }}
    name: {{ .Values.sentinel.name }}
  selector:
    app: {{ .Values.sentinel.name }}